In [1]:
import torch

In [3]:
print(torch.__version__)
print(torch.cuda.is_available())

2.7.0+cu128
True


In [7]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
x.device

device(type='cpu')

In [11]:
x.shape

torch.Size([2, 3])

In [17]:
x.size()

torch.Size([2, 3])

In [21]:
x = torch.empty((2,2))

In [23]:
x

tensor([[-1.6512e+04,  1.5596e-42],
        [ 0.0000e+00,  0.0000e+00]])

In [25]:
x = torch.zeros((2,2))

In [27]:
x

tensor([[0., 0.],
        [0., 0.]])

In [29]:
x = torch.zeros((2,2), dtype = int)

In [31]:
x

tensor([[0, 0],
        [0, 0]])

In [33]:
torch.rand(4)

tensor([0.6626, 0.3670, 0.2235, 0.2612])

In [35]:
torch.rand(4,4)

tensor([[0.9295, 0.2251, 0.5631, 0.3447],
        [0.8454, 0.1034, 0.8417, 0.7178],
        [0.0831, 0.9507, 0.7409, 0.1183],
        [0.4065, 0.4737, 0.7591, 0.3138]])

In [39]:
torch.rand((4,4), dtype=int)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [41]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [43]:
torch.eye(2,2, dtype=int)

tensor([[1, 0],
        [0, 1]])

In [45]:
torch.arange(1,5)

tensor([1, 2, 3, 4])

In [47]:
torch.arange(1,5,2)

tensor([1, 3])

In [61]:
x = torch.diag(torch.tensor([1,2,3]))

In [63]:
x

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [65]:
x.bool()

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [67]:
x.short()

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]], dtype=torch.int16)

In [69]:
x.float()

tensor([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 3.]])

In [71]:
import numpy as np

In [73]:
n = np.zeros((3,3))

In [75]:
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
t =torch.from_numpy(n)

In [79]:
t

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [81]:
n = t.numpy()

In [101]:
x =  torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [87]:
torch.add(x,y)

tensor([5, 7, 9])

In [89]:
x+y

tensor([5, 7, 9])

In [91]:
y-x

tensor([3, 3, 3])

In [93]:
y/x

tensor([4.0000, 2.5000, 2.0000])

In [105]:
x.add(y)

tensor([5, 7, 9])

In [107]:
x

tensor([1, 2, 3])

In [113]:
x.add_(y)#inplce

tensor([ 9, 12, 15])

In [115]:
x

tensor([ 9, 12, 15])

In [117]:
x>0

tensor([True, True, True])

In [119]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

In [121]:
torch.mm(x1,x2)

tensor([[1.0591, 0.6618, 1.2926],
        [1.3858, 0.8887, 1.4134]])

In [123]:
x1.mm(x2)

tensor([[1.0591, 0.6618, 1.2926],
        [1.3858, 0.8887, 1.4134]])

In [125]:
x1@x2

tensor([[1.0591, 0.6618, 1.2926],
        [1.3858, 0.8887, 1.4134]])

In [141]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

In [143]:
x1,x2

(tensor([[0.0342, 0.1267, 0.5581, 0.2236, 0.0235],
         [0.0093, 0.0094, 0.7368, 0.2549, 0.0613],
         [0.4196, 0.4238, 0.5091, 0.2255, 0.2806],
         [0.0529, 0.2920, 0.4533, 0.4771, 0.2579],
         [0.5884, 0.0661, 0.3211, 0.3416, 0.1504]]),
 tensor([[0.2516, 0.5918, 0.8701, 0.6481, 0.9264]]))

In [145]:
x1-x2 #broadcasting

tensor([[-0.2175, -0.4651, -0.3120, -0.4245, -0.9030],
        [-0.2423, -0.5824, -0.1333, -0.3932, -0.8651],
        [ 0.1680, -0.1680, -0.3610, -0.4226, -0.6458],
        [-0.1987, -0.2998, -0.4167, -0.1710, -0.6685],
        [ 0.3368, -0.5257, -0.5489, -0.3065, -0.7760]])

In [147]:
x2 = torch.rand((2,5))

In [149]:
x1-x2 #broadcasting

RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 0

In [151]:
torch.max(x)

tensor(15)

In [153]:
x

tensor([ 9, 12, 15])

In [155]:
torch.max(x1)

tensor(0.7368)

In [157]:
torch.max(x1, dim=0)

torch.return_types.max(
values=tensor([0.5884, 0.4238, 0.7368, 0.4771, 0.2806]),
indices=tensor([4, 2, 1, 3, 2]))

In [161]:
torch.clamp(x ,min=10) # clamps every value which is less than 10 to 10 > kinda Relu

tensor([10, 12, 15])

In [164]:
batch_size =10
features = 25

In [168]:
x = torch.rand((batch_size, features))

In [170]:
x.shape

torch.Size([10, 25])

In [172]:
x[0]

tensor([0.3467, 0.6655, 0.1635, 0.5400, 0.0358, 0.4740, 0.3850, 0.6049, 0.9957,
        0.5833, 0.6898, 0.4065, 0.8471, 0.3490, 0.1911, 0.3142, 0.0011, 0.3067,
        0.4068, 0.6222, 0.7289, 0.9200, 0.4148, 0.8884, 0.7108])

In [174]:
x[:,0]

tensor([0.3467, 0.5493, 0.9208, 0.2840, 0.3391, 0.2580, 0.4026, 0.6963, 0.1739,
        0.1247])

In [176]:
x[2,0:10]

tensor([0.9208, 0.6711, 0.2459, 0.9881, 0.0819, 0.0846, 0.8028, 0.4711, 0.1692,
        0.1305])

In [178]:
x[0,0]

tensor(0.3467)

In [180]:
x[0,0] = 100

In [182]:
x[0,0]


tensor(100.)

In [184]:
x[0]

tensor([1.0000e+02, 6.6548e-01, 1.6346e-01, 5.4001e-01, 3.5805e-02, 4.7402e-01,
        3.8496e-01, 6.0486e-01, 9.9575e-01, 5.8330e-01, 6.8983e-01, 4.0650e-01,
        8.4707e-01, 3.4898e-01, 1.9109e-01, 3.1419e-01, 1.1196e-03, 3.0671e-01,
        4.0677e-01, 6.2219e-01, 7.2891e-01, 9.2000e-01, 4.1483e-01, 8.8843e-01,
        7.1076e-01])

In [186]:
x = torch.arange(10)

In [188]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
x[x>4]

tensor([5, 6, 7, 8, 9])

In [196]:
torch.where(x>5 ,x, x+9)

tensor([ 9, 10, 11, 12, 13, 14,  6,  7,  8,  9])

In [200]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
x.ndimension()

1

In [206]:
x.numel()#number of elemnets

10

In [208]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
x.view(3,3)

RuntimeError: shape '[3, 3]' is invalid for input of size 10

In [212]:
x = torch.arange(9)

In [214]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [216]:
torch.rand(9)

tensor([0.2365, 0.8970, 0.0642, 0.2845, 0.1895, 0.0299, 0.9382, 0.7476, 0.8534])

In [224]:
y = x.view(3,3)

In [226]:
y

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [220]:
x.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [228]:
y.t()

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [230]:
y.view(9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [232]:
y.t().view(9)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [234]:
t.contiguous().view(9)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

In [238]:
y.view(-1)#flatten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [240]:
x = torch.arange(10)

In [248]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [242]:
x.unsqueeze(0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [244]:
x.unsqueeze(0).shape

torch.Size([1, 10])

In [246]:
x.unsqueeze(1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [250]:
x.squeeze(1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Neural Network

In [253]:
import torch.nn as nn

In [257]:
import torch.optim as optim # optimizers like adam

In [259]:
import torch.nn.functional as F # Functions that dont have parameters like Relu, tanh

In [263]:
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [267]:
#create fully connected layer

class NN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NN, self).__init__()
        self.layer1 = nn.Linear(input_size , 50) # x1w1*x2w2*….x784*w784 and then distribute to 50 neurons -> A
        self.layer2 = nn.Linear(50 , num_classes)
    def forward(self, x):#where connection between layers happens
        x = F.relu(self.layer1(x))#for A we apply relu
        x = self.layer2(x)
        return x
    

In [275]:
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') 

In [277]:
device = torch.device("cuda")

In [297]:
#Hyperparameters

input_size = 784
num_classes = 10
learning_rate = 0.001
batch_size = 64 # divide input data into 64 > 60,000 ÷ 64 ≈ 937 batches
num_epochs = 1

In [283]:
#data load

train_data = datasets.MNIST(root = 'dataset/', train=True, transform=transforms.ToTensor(), download =True)
test_data = datasets.MNIST(root = 'dataset/', train=False, transform=transforms.ToTensor(), download =True)

100%|█████████████████████████████████████████████████████████████████████████████| 9.91M/9.91M [00:00<00:00, 20.6MB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 28.9k/28.9k [00:00<00:00, 3.16MB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 1.65M/1.65M [00:00<00:00, 15.5MB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 4.54k/4.54k [00:00<00:00, 3.76MB/s]


In [287]:
train_loader = DataLoader(dataset = train_data, batch_size = batch_size, shuffle =True)
test_loader = DataLoader(dataset = test_data, batch_size = batch_size, shuffle =True)

In [289]:
test_loader

In [291]:
for images, labels in test_loader:
    print(images.shape)  # Shape of one batch
    print(labels.shape)  # Shape of the labels
    break  # Important! Otherwise it'll print all batches


torch.Size([64, 1, 28, 28])
torch.Size([64])


In [293]:
#initialize network
model = NN(input_size = input_size, num_classes =num_classes).to(device)

In [301]:
#Loss and optimzer

creiterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

In [303]:
########################### Train Network  ##############################

for e in range(num_epochs):
    for batch_idx ,(data,targets) in enumerate(train_loader):
        data = data.to(device=device)
        targets = targets.to(device =device)

        #changing the shape of input features in [1, 28, 28] into 784
        data =  data.reshape(data.shape[0] ,-1) # [64, 1, 28, 28] == [64, -1] == [64, flatten=784]

        #forward
        scores = model(data)
        loss = creiterion(scores,targets)

        #backward
        optimizer.zero_grad() # grad=0 for every run ..but weights will be using old iteration weights
        loss.backward() # calculating gradient

        optimizer.step()# updating the weight
        


In [313]:
def check_accuracy(loader, model):
    if loader.dataset.train:
        print("Train datset check")
    else:
        print("Test dataset check")

    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():#In with torch.no_grad(), you only use the model's already learned weights to predict outputs, without touching them.-scores = model(x)
#          If you skip torch.no_grad(), then: PyTorch still tracks all operations for autograd.
            # It builds a computation graph in memory even though you're not training.
             # BUT (important!) it does NOT update weights automatically.
        for x,y in loader:
            x = x.to(device =device)
            y = y.to(device =device)
            x = x.reshape(x.shape[0],-1)

            scores = model(x)
            _,pred = scores.max(1)
            num_correct += (pred == y).sum()
            num_samples += pred.size(0)
        print(f" got {num_correct} / {num_samples} with accuracy of {float(num_correct/num_samples)*100:.2f}")
    model.train()

In [315]:
check_accuracy(test_loader,model)

Test dataset check
 got 9276 / 10000 with accuracy of 92.76


In [309]:
check_accuracy(train_loader,model)

Train datset check
 got 55660 / 60000 with accuracy of 92.77


In [319]:
from torchmetrics.classification import Accuracy

metric = Accuracy(task="multiclass", num_classes=10).to(device)

for x, y in test_loader:
    x = x.to(device)
    y = y.to(device)
    x = x.reshape(x.shape[0], -1)
    scores = model(x)
    _, pred = scores.max(1)
    metric.update(pred, y)

print(metric.compute())

tensor(0.9276, device='cuda:0')


In [317]:
# pip install torchmetrics


   ---------------------------------------- 0.0/961.5 kB ? eta -:--:--
   --------------------------------------- 961.5/961.5 kB 43.7 MB/s eta 0:00:00


### CNN

In [348]:
#create fully connected layer

class CNN(nn.Module):
    def __init__(self, in_channels =1 , out_channels =10):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels , out_channels = 8, kernel_size = (3,3), stride =(1,1), padding=(1,1))
        self.pool = nn.MaxPool2d(kernel_size = (2,2), stride=(2,2))
        self.conv2 = nn.Conv2d(in_channels=8, out_channels =16, kernel_size = (3,3), stride =(1,1), padding=(1,1))
        self.layer1 = nn.Linear(16*7*7, num_classes)
    def forward(self, x):#where connection between layers happens
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
        x = x.reshape(x.shape[0], -1)#flatten
        x = self.layer1(x)
        return x
    

In [350]:
device = torch.device("cuda")


#Hyperparameters

in_channels = 1 #as it is black and white
out_channels = 10
learning_rate = 0.001
batch_size = 64 # divide input data into 64 > 60,000 ÷ 64 ≈ 937 batches
num_epochs = 1


# #data load

# train_data = datasets.MNIST(root = 'dataset/', train=True, transform=transforms.ToTensor(), download =True)
# test_data = datasets.MNIST(root = 'dataset/', train=False, transform=transforms.ToTensor(), download =True)


# train_loader = DataLoader(dataset = train_data, batch_size = batch_size, shuffle =True)
# test_loader = DataLoader(dataset = test_data, batch_size = batch_size, shuffle =True)

#initialize network
model = CNN().to(device)

#Loss and optimzer

creiterion = nn.CrossEntropyLoss()#CrossEntropyLoss expects raw logits and internally applies softmax (normalization) to turn them into probabilities.
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

########################### Train Network  ##############################

for e in range(num_epochs):
    for batch_idx ,(data,targets) in enumerate(train_loader):
        data = data.to(device=device)
        targets = targets.to(device =device)

        #changing the shape of input features in [1, 28, 28] into 784
        # data =  data.reshape(data.shape[0] ,-1) # [64, 1, 28, 28] == [64, -1] == [64, flatten=784]

        #forward
        scores = model(data)
        loss = creiterion(scores,targets)

        #backward
        optimizer.zero_grad() # grad=0 for every run ..but weights will be using old iteration weights
        loss.backward() # calculating gradient

        optimizer.step()# updating the weight
        



In [352]:
##############################Accuracy#####################
def check_accuracy(loader, model):
    if loader.dataset.train:
        print("Train datset check")
    else:
        print("Test dataset check")

    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():#In with torch.no_grad(), you only use the model's already learned weights to predict outputs, without touching them.-scores = model(x)
#          If you skip torch.no_grad(), then: PyTorch still tracks all operations for autograd.
            # It builds a computation graph in memory even though you're not training.
             # BUT (important!) it does NOT update weights automatically.
        for x,y in loader:
            x = x.to(device =device)
            y = y.to(device =device)
            # x = x.reshape(x.shape[0],-1)

            scores = model(x)
            _,pred = scores.max(1)
            num_correct += (pred == y).sum()
            num_samples += pred.size(0)
        print(f" got {num_correct} / {num_samples} with accuracy of {float(num_correct/num_samples)*100:.2f}")
    model.train()
        
check_accuracy(test_loader,model)

Test dataset check
 got 9686 / 10000 with accuracy of 96.86


So first there will be inputs lets say in MNIST each photo has 784 pixels or inputs …so in first layer we will have 784 neurons and then we calculate x1w1*x2w2*….x784*w784 this value we pass to every hidden layer neuron say there are 50 hidden layers where lets say there will be activation RELU which makes value between -1 and +1 

**Input layer has features, not neurons** → real neurons start in hidden layers. - Correction

- Inputs = 784.
- First hidden layer = 50 neurons (not 784 neurons again).



so for all 50 values from hidden layer form this s shape distribution and again all will do forward calculation   x1w1*x2w2*….x50*w50 and lets say there is another hidden layer of 50 neurons again it does then dame finally there will be 10 neurons of output later

this is total forward pass

then we calculate  loss,

then we calculate backward i.e gradient for all neurons

then we do optimize

lets say gradient is -0.02

then w = -0.01* gradient (learning rate=0.01)

we follow the same process for many times

✅So **because of non-linear activations differentiation** and **gradient descent** can actually "navigate" complicated loss surfaces (full of hills, valleys, curves).

✅ **you apply ReLU after each hidden layer**,

✅ **except** after the **final output layer**.

Each hidden layer needs **non-linearity** (ReLU) so the model can learn **complex transformations**.

✅ **Bias is automatically included inside `nn.Linear` layer itself!**

```python
class NeuralNet(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)  # 1st hidden layer
        self.fc2 = nn.Linear(128, 64)           # 2nd hidden layer
        self.fc3 = nn.Linear(64, 32)            # 3rd hidden layer
        self.fc_out = nn.Linear(32, num_classes) # output layer

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc_out(x)  # No activation here
        return x

```

**1 epoch meaning** -

| Item | Value |
| --- | --- |
| Training data | 60,000 images |
| Batch size | 64 |
| Number of batches | 60,000 ÷ 64 ≈ 937 batches |

➡️ In **one epoch**, your model **updates weights ~937 times**!

**NOT** just once.

Initial Weights (random)

Batch 1:
Inputs: Images 1-64
Forward → Loss → Backward → Update weights

Batch 2:
Inputs: Images 65-128
Forward (with new weights) → Loss → Backward → Update weights

Batch 3:
Inputs: Images 129-192
Forward (with even newer weights) → Loss → Backward → Update weights

...and so on, until all batches are done → 1 epoch completed.