In [3]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline 

In [25]:
words = open('names.txt', 'r').read().splitlines()

In [41]:
words[2]

'ava'

In [39]:
set(words[2])

{'a', 'v'}

In [27]:
chars = sorted(list(set(''.join(words))))

In [45]:
stoi = {s:i+1 for i,s in enumerate(chars)}

In [47]:
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [233]:
blocksize=3
X,Y = [],[]

for w in words[:5]:
    #print(w)
    context = [0]*blocksize
    for ch in w+'.':
        # print(ch)
        ix=stoi[ch]
        X.append(context)
        Y.append(ix)
        #
        print (''.join(itos[i] for i in context), '-->', itos[ix])
        context =context[1:]+[ix]
print(X)
X = torch.tensor(X)
print(X)
Y = torch.tensor(Y)
        
        

... --> e
..e --> m
.em --> m
emm --> a
mma --> .
... --> o
..o --> l
.ol --> i
oli --> v
liv --> i
ivi --> a
via --> .
... --> a
..a --> v
.av --> a
ava --> .
... --> i
..i --> s
.is --> a
isa --> b
sab --> e
abe --> l
bel --> l
ell --> a
lla --> .
... --> s
..s --> o
.so --> p
sop --> h
oph --> i
phi --> a
hia --> .
[[0, 0, 0], [0, 0, 5], [0, 5, 13], [5, 13, 13], [13, 13, 1], [0, 0, 0], [0, 0, 15], [0, 15, 12], [15, 12, 9], [12, 9, 22], [9, 22, 9], [22, 9, 1], [0, 0, 0], [0, 0, 1], [0, 1, 22], [1, 22, 1], [0, 0, 0], [0, 0, 9], [0, 9, 19], [9, 19, 1], [19, 1, 2], [1, 2, 5], [2, 5, 12], [5, 12, 12], [12, 12, 1], [0, 0, 0], [0, 0, 19], [0, 19, 15], [19, 15, 16], [15, 16, 8], [16, 8, 9], [8, 9, 1]]
tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        

In [23]:
c=[0]*10
c

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [61]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [65]:
#lookup table

C= torch.randn((27,2))

In [75]:
C

tensor([[ 0.2374, -0.8679],
        [-0.2788,  1.2282],
        [-2.8233,  0.6397],
        [-1.0845, -2.7669],
        [-0.4035,  0.6368],
        [-0.5516, -0.2694],
        [ 1.5011, -0.2377],
        [ 0.2090,  0.1217],
        [ 0.5346,  0.0618],
        [-0.8681,  1.7609],
        [-1.0644,  1.0225],
        [ 1.2170, -0.1852],
        [-0.2014,  0.8887],
        [ 0.0588, -2.1722],
        [-1.9443, -0.7860],
        [ 1.2660,  1.3129],
        [ 0.1812,  1.0343],
        [-0.6800,  0.3471],
        [-1.9825, -0.8652],
        [-1.7578, -1.0175],
        [ 0.0846, -0.6429],
        [ 0.8926, -0.1261],
        [ 0.3042, -2.1388],
        [ 1.9180,  0.6863],
        [ 1.1518,  0.1614],
        [-1.4213,  0.1716],
        [ 0.2499, -1.1691]])

In [67]:
C[5]

tensor([-0.5516, -0.2694])

In [71]:
F.one_hot(torch.tensor(5), num_classes=27)

tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

In [73]:
 F.one_hot(torch.tensor(5), num_classes=27).float()@ C

tensor([-0.5516, -0.2694])

In [79]:
C[[5,6,7]]

tensor([[-0.5516, -0.2694],
        [ 1.5011, -0.2377],
        [ 0.2090,  0.1217]])

In [81]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [87]:
C[X]

tensor([[[ 0.2374, -0.8679],
         [ 0.2374, -0.8679],
         [ 0.2374, -0.8679]],

        [[ 0.2374, -0.8679],
         [ 0.2374, -0.8679],
         [-0.5516, -0.2694]],

        [[ 0.2374, -0.8679],
         [-0.5516, -0.2694],
         [ 0.0588, -2.1722]],

        [[-0.5516, -0.2694],
         [ 0.0588, -2.1722],
         [ 0.0588, -2.1722]],

        [[ 0.0588, -2.1722],
         [ 0.0588, -2.1722],
         [-0.2788,  1.2282]],

        [[ 0.2374, -0.8679],
         [ 0.2374, -0.8679],
         [ 0.2374, -0.8679]],

        [[ 0.2374, -0.8679],
         [ 0.2374, -0.8679],
         [ 1.2660,  1.3129]],

        [[ 0.2374, -0.8679],
         [ 1.2660,  1.3129],
         [-0.2014,  0.8887]],

        [[ 1.2660,  1.3129],
         [-0.2014,  0.8887],
         [-0.8681,  1.7609]],

        [[-0.2014,  0.8887],
         [-0.8681,  1.7609],
         [ 0.3042, -2.1388]],

        [[-0.8681,  1.7609],
         [ 0.3042, -2.1388],
         [-0.8681,  1.7609]],

        [[ 0.3042, -2

In [89]:
emb=C[X]

In [91]:
emb.shape

torch.Size([32, 3, 2])

In [97]:
# 3*2=6

In [103]:
#hidden layer

In [ ]:
# emb@w1+b

In [131]:
w1= torch.randn((6,100))
b1= torch.randn(100)

In [133]:
torch.randn((6,4))

tensor([[-1.5116,  1.4578,  0.1976,  0.5708],
        [ 1.1077, -0.2818, -1.4572,  0.5754],
        [ 0.2145,  0.2935,  0.0215, -0.7241],
        [ 0.5133,  1.9163,  0.4333,  0.6484],
        [ 0.9235,  2.2075, -1.7004,  0.1253],
        [ 0.8860, -1.8671,  1.0910,  0.3701]])

In [135]:
# to match the dimension of emb and w1 we use view
a=torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
a.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [145]:
# h= emb.view(32,6)@w1+b1

In [147]:
h= emb.view(emb.shape[0],6)@w1+b1 #h= emb.view(-1,6)@w1+b1 

In [151]:
h.shape

torch.Size([32, 100])

In [153]:
# Final Layer

In [159]:
w2 = torch.randn((100,27))
b2= torch.randn(27)

In [163]:
logits = h @ w2 +b2

In [165]:
counts = logits.exp()

In [167]:
prob=counts/counts.sum(1, keepdims=True)

In [171]:
prob.shape

torch.Size([32, 27])

In [175]:
prob[0].sum()

tensor(1.)

In [177]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [179]:
torch.arange(32)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [183]:
prob[1,0]

tensor(1.1090e-18)

In [185]:
prob[torch.arange(32),Y]

tensor([8.1456e-29, 2.4528e-25, 2.6033e-34, 0.0000e+00, 1.0851e-10, 1.2958e-35,
        6.6653e-24, 1.4808e-34, 9.3168e-20, 1.0816e-03, 1.8964e-32, 8.9701e-18,
        5.9414e-22, 1.8090e-22, 1.7412e-25, 6.7448e-23, 4.4257e-35, 1.1204e-13,
        8.5225e-12, 1.7976e-23, 3.1051e-19, 1.3400e-06, 1.0000e+00, 2.0594e-09,
        3.5387e-13, 1.4845e-23, 9.4270e-29, 3.4817e-23, 2.3836e-07, 1.3446e-14,
        9.3715e-09, 1.2139e-10])

In [187]:
loss = -prob[torch.arange(32),Y].log().mean()

In [201]:
#PUTTING ALL TOGETHER

In [251]:
#dataset
blocksize=3
X,Y = [],[]

for w in words:
    #print(w)
    context = [0]*blocksize
    for ch in w+'.':
        # print(ch)
        ix=stoi[ch]
        X.append(context)
        Y.append(ix)
        #
        # print (''.join(itos[i] for i in context), '-->', itos[ix])
        context =context[1:]+[ix]
# print(X)
X = torch.tensor(X)
# print(X)
Y = torch.tensor(Y)

In [253]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([228146, 3]), torch.int64, torch.Size([228146]), torch.int64)

In [289]:
g = torch.Generator().manual_seed(2147483647) # for reproducibility
C = torch.randn((27, 2), generator=g)
W1 = torch.randn((6, 100), generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100, 27), generator=g)
b2 = torch.randn(27, generator=g)
parameters = [C, W1, b1, W2, b2]

In [257]:
sum(p.nelement() for p in parameters) # count

3481

In [199]:
emb = C[X] # (32, 3, 2)
h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
logits = h @ W2 + b2 # (32, 27)
counts = logits.exp()
prob=counts/counts.sum(1, keepdims=True)
loss = -prob[torch.arange(32),Y].log().mean()
loss

tensor(17.7697)

In [203]:
emb = C[X] # (32, 3, 2)
h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
logits = h @ W2 + b2 # (32, 27)
# counts = logits.exp()
# prob=counts/counts.sum(1, keepdims=True)
# loss = -prob[torch.arange(32),Y].log().mean()
loss = F.cross_entropy(logits,Y)

In [205]:
loss

tensor(17.7697)

In [209]:
#cross_entropy is very use ful than the earlier mentod as its memory effocient and neumerical effieienct forward and backward pass

In [215]:
logits =torch.tensor([-5,0,-2,500])
counts = logits.exp()
counts

tensor([0.0067, 1.0000, 0.1353,    inf])

In [217]:
logits =torch.tensor([-5,0,-2,500])-500
counts = logits.exp()
counts

tensor([0., 0., 0., 1.])

In [219]:
#cross_entropy uses 2nd method

In [295]:
for p in parameters:
    p.requires_grad= True

In [263]:
for _ in range(10):
# forwardpass
    emb = C[X] # (32, 3, 2)
    h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
    logits = h @ W2 + b2 # (32, 27)
    loss = F.cross_entropy(logits,Y)
    print(loss)
    #backward pass
    for p in parameters:
        p.grad=None
    loss.backward()
    #update
    for p in parameters:
        p.data += -0.1* p.grad
print(loss.item())

tensor(19.5052, grad_fn=<NllLossBackward0>)
tensor(17.0845, grad_fn=<NllLossBackward0>)
tensor(15.7765, grad_fn=<NllLossBackward0>)
tensor(14.8333, grad_fn=<NllLossBackward0>)
tensor(14.0026, grad_fn=<NllLossBackward0>)
tensor(13.2533, grad_fn=<NllLossBackward0>)
tensor(12.5799, grad_fn=<NllLossBackward0>)
tensor(11.9831, grad_fn=<NllLossBackward0>)
tensor(11.4705, grad_fn=<NllLossBackward0>)
tensor(11.0519, grad_fn=<NllLossBackward0>)
11.051864624023438


In [231]:
# loss is reducing easily as we have 3400 parameters and 32 examples . we are doing overfitting

In [279]:
#Batch Processing - to run quicker

In [269]:
torch.randint(0,5,(32,))# 32 elements from 0-5s

tensor([4, 3, 1, 3, 3, 4, 1, 4, 1, 4, 2, 1, 4, 1, 4, 1, 3, 0, 3, 3, 1, 1, 1, 3,
        2, 4, 0, 4, 4, 1, 2, 4])

In [273]:
torch.randint(0,X.shape[0],(32,))# selecting random 32 elements and run the model on this batch of 32

tensor([167886, 183482,  58344, 134277,  52019, 203838, 148555,  98393, 164645,
         67961,  23734, 123038,  34701,  14904, 225056, 195945, 171782,  10200,
         41414,  81922, 214356,  10950,   1684,  32756,  51032,  73928, 210864,
        138870, 178159, 150023, 114285,  51274])

In [275]:
C[X[[3,3,4]]]

tensor([[[-0.4806,  0.5774],
         [ 2.3819, -0.6509],
         [ 2.3819, -0.6509]],

        [[-0.4806,  0.5774],
         [ 2.3819, -0.6509],
         [ 2.3819, -0.6509]],

        [[ 2.3819, -0.6509],
         [ 2.3819, -0.6509],
         [ 0.0902, -1.0768]]], grad_fn=<IndexBackward0>)

In [297]:
for _ in range(10):

    #minibatch
    ix =torch.randint(0,X.shape[0],(32,))# selecting random 32 elements and run the model on this batch of 32
    
    # forwardpass
    emb = C[X[ix]] # (32, 3, 2)
    h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
    logits = h @ W2 + b2 # (32, 27)
    loss = F.cross_entropy(logits,Y[ix])
    print(loss)
    #backward pass
    for p in parameters:
        p.grad=None
    loss.backward()
    #update
    for p in parameters:
        p.data += -0.1* p.grad
print(loss.item())

tensor(21.5985, grad_fn=<NllLossBackward0>)
tensor(18.6412, grad_fn=<NllLossBackward0>)
tensor(16.4533, grad_fn=<NllLossBackward0>)
tensor(15.4423, grad_fn=<NllLossBackward0>)
tensor(15.0832, grad_fn=<NllLossBackward0>)
tensor(10.6260, grad_fn=<NllLossBackward0>)
tensor(15.1152, grad_fn=<NllLossBackward0>)
tensor(12.3243, grad_fn=<NllLossBackward0>)
tensor(10.3950, grad_fn=<NllLossBackward0>)
tensor(11.5743, grad_fn=<NllLossBackward0>)
11.574263572692871


In [281]:

# as we are having only 32 examples the gradient will not be consistently lower compared to 228146 X but this  process is quick and good estimation

In [299]:
#loss for whole batch
emb = C[X] # (32, 3, 2)
h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
logits = h @ W2 + b2 # (32, 27)
loss = F.cross_entropy(logits,Y)
loss

tensor(10.8737, grad_fn=<NllLossBackward0>)

In [287]:
#learningrate

In [305]:
torch.linspace(0.001, 1,10) # give linerly

tensor([0.0010, 0.1120, 0.2230, 0.3340, 0.4450, 0.5560, 0.6670, 0.7780, 0.8890,
        1.0000])

In [311]:
lre = torch.linspace(-3, 0,10)#10^-3 =0.001
lrs = 10**lre
lrs # spaced exponentially

tensor([0.0010, 0.0022, 0.0046, 0.0100, 0.0215, 0.0464, 0.1000, 0.2154, 0.4642,
        1.0000])

In [315]:
lri=[]
lossi=[]
for i in range(10):

    #minibatch
    ix =torch.randint(0,X.shape[0],(32,))# selecting random 32 elements and run the model on this batch of 32
    
    # forwardpass
    emb = C[X[ix]] # (32, 3, 2)
    h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
    logits = h @ W2 + b2 # (32, 27)
    loss = F.cross_entropy(logits,Y[ix])
    print(loss)
    #backward pass
    for p in parameters:
        p.grad=None
    loss.backward()
    #update
    lr=lrs[i]
    for p in parameters:
        p.data += -lr* p.grad

    #track ststs
print(loss.item())

tensor(8.5197, grad_fn=<NllLossBackward0>)
tensor(7.8887, grad_fn=<NllLossBackward0>)
tensor(9.2668, grad_fn=<NllLossBackward0>)
tensor(7.0164, grad_fn=<NllLossBackward0>)
tensor(8.0321, grad_fn=<NllLossBackward0>)
tensor(7.3275, grad_fn=<NllLossBackward0>)
tensor(8.6169, grad_fn=<NllLossBackward0>)
tensor(8.5474, grad_fn=<NllLossBackward0>)
tensor(7.3330, grad_fn=<NllLossBackward0>)
tensor(7.5935, grad_fn=<NllLossBackward0>)
7.5934739112854
